import { Region } from "@src/types/store/regionesStore";

export const regiones: Region[] = [
    {
        id: 1,
        nombre: "Arica y Parinacota",
        capital: "Arica",
        ciudades: [
            { nombre: "Arica" },
            { nombre: "Putre" },
            { nombre: "Visviri" },
            { nombre: "Camarones" },
        ],
    },
    {
        id: 2,
        nombre: "Tarapacá",
        capital: "Iquique",
        ciudades: [
            { nombre: "Iquique" },
            { nombre: "Alto Hospicio" },
            { nombre: "Pozo Almonte" },
            { nombre: "Pica" },
            { nombre: "Huara" },
        ],
    },
    {
        id: 3,
        nombre: "Antofagasta",
        capital: "Antofagasta",
        ciudades: [
            { nombre: "Antofagasta" },
            { nombre: "Calama" },
            { nombre: "Tocopilla" },
            { nombre: "Mejillones" },
            { nombre: "San Pedro de Atacama" },
            { nombre: "Sierra Gorda" },
            { nombre: "Antofagasta" },
        ],
    },
    {
        id: 4,
        nombre: "Atacama",
        capital: "Copiapó",
        ciudades: [
            { nombre: "Copiapó" },
            { nombre: "Vallenar" },
            { nombre: "Caldera" },
            { nombre: "Freirina" },
            { nombre: "Tierra Amarilla" },
            { nombre: "Huasco" },
        ],
    },
    {
        id: 5,
        nombre: "Coquimbo",
        capital: "La Serena",
        ciudades: [
            { nombre: "La Serena" },
            { nombre: "Coquimbo" },
            { nombre: "Ovalle" },
            { nombre: "Illapel" },
            { nombre: "Los Vilos" },
            { nombre: "Andacollo" },
            { nombre: "La Higuera" },
        ],
    },
    {
        id: 6,
        nombre: "Valparaíso",
        capital: "Valparaíso",
        ciudades: [
            { nombre: "Valparaíso" },
            { nombre: "Viña del Mar" },
            { nombre: "San Antonio" },
            { nombre: "Quilpué" },
            { nombre: "Villa Alemana" },
            { nombre: "Los Andes" },
            { nombre: "San Felipe" },
            { nombre: "Concón" },
        ],
    },
    {
        id: 7,
        nombre: "Metropolitana de Santiago",
        capital: "Santiago",
        ciudades: [
            { nombre: "Santiago" },
            { nombre: "Maipú" },
            { nombre: "Las Condes" },
            { nombre: "Providencia" },
            { nombre: "La Florida" },
            { nombre: "Puente Alto" },
            { nombre: "San Bernardo" },
            { nombre: "Renca" },
            { nombre: "Estación Central" },
            { nombre: "Quilicura" },
            { nombre: "La Pintana" },
            { nombre: "La Cisterna" },
        ],
    },
    {
        id: 8,
        nombre: "O'Higgins",
        capital: "Rancagua",
        ciudades: [
            { nombre: "Rancagua" },
            { nombre: "San Fernando" },
            { nombre: "Pichilemu" },
            { nombre: "Rengo" },
            { nombre: "Graneros" },
            { nombre: "Codegua" },
            { nombre: "Malloa" },
            { nombre: "Placilla" },
            { nombre: "Machalí" },
        ],
    },
    {
        id: 9,
        nombre: "Maule",
        capital: "Talca",
        ciudades: [
            { nombre: "Talca" },
            { nombre: "Curicó" },
            { nombre: "Linares" },
            { nombre: "San Javier" },
            { nombre: "Maule" },
            { nombre: "Constitución" },
            { nombre: "Cauquenes" },
            { nombre: "Sagrada Familia" },
            { nombre: "Hualañé" },
            { nombre: "Teno" },
        ],
    },
    {
        id: 10,
        nombre: "Ñuble",
        capital: "Chillán",
        ciudades: [
            { nombre: "Chillán" },
            { nombre: "Los Ángeles" },
            { nombre: "Ninhue" },
            { nombre: "Yungay" },
            { nombre: "Quirihue" },
            { nombre: "Pinto" },
            { nombre: "San Carlos" },
            { nombre: "Coihueco" },
            { nombre: "San Nicolás" },
            { nombre: "El Carmen" },
        ],
    },
    {
        id: 11,
        nombre: "Biobío",
        capital: "Concepción",
        ciudades: [
            { nombre: "Concepción" },
            { nombre: "Talcahuano" },
            { nombre: "Los Ángeles" },
            { nombre: "Chiguayante" },
            { nombre: "San Pedro de la Paz" },
            { nombre: "Hualpén" },
            { nombre: "Penco" },
            { nombre: "Coronel" },
            { nombre: "Lota" },
            { nombre: "Tomé" },
            { nombre: "Hualqui" },
            { nombre: "Santa Juana" },
        ],
    },
    {
        id: 12,
        nombre: "La Araucanía",
        capital: "Temuco",
        ciudades: [
            { nombre: "Temuco" },
            { nombre: "Villarrica" },
            { nombre: "Pucón" },
            { nombre: "Angol" },
            { nombre: "Cautín" },
            { nombre: "Victoria" },
            { nombre: "Lautaro" },
            { nombre: "Curacautín" },
            { nombre: "Padre Las Casas" },
            { nombre: "Traiguén" },
        ],
    },
    {
        id: 13,
        nombre: "Los Ríos",
        capital: "Valdivia",
        ciudades: [
            { nombre: "Valdivia" },
            { nombre: "Lanco" },
            { nombre: "La Unión" },
            { nombre: "Panguipulli" },
            { nombre: "Río Bueno" },
            { nombre: "Corral" },
            { nombre: "Mariquina" },
            { nombre: "Futrono" },
            { nombre: "Los Lagos" },
            { nombre: "Ranco" },
        ],
    },
    {
        id: 14,
        nombre: "Los Lagos",
        capital: "Puerto Montt",
        ciudades: [
            { nombre: "Puerto Montt" },
            { nombre: "Osorno" },
            { nombre: "Puerto Varas" },
            { nombre: "Frutillar" },
            { nombre: "Castro" },
            { nombre: "Ancud" },
            { nombre: "Calbuco" },
            { nombre: "Chonchi" },
            { nombre: "Hualaihué" },
            { nombre: "La Unión" },
            { nombre: "Puerto Octay" },
        ],
    },
    {
        id: 15,
        nombre: "Aysén del General Carlos Ibáñez del Campo",
        capital: "Coyhaique",
        ciudades: [
            { nombre: "Coyhaique" },
            { nombre: "Puerto Aysén" },
            { nombre: "Chile Chico" },
            { nombre: "Cisnes" },
            { nombre: "Puyuhuapi" },
            { nombre: "Aysén" },
            { nombre: "Raúl Marín Balmaceda" },
            { nombre: "Lago Verde" },
        ],
    },
    {
        id: 16,
        nombre: "Magallanes y de la Antártica Chilena",
        capital: "Punta Arenas",
        ciudades: [
            { nombre: "Punta Arenas" },
            { nombre: "Puerto Natales" },
            { nombre: "Porvenir" },
            { nombre: "Cabo de Hornos" },
            { nombre: "Puerto Williams" },
            { nombre: "Río Verde" },
            { nombre: "Lago Blanco" },
        ],
    },
];
